name: Install
description: install dependencies

inputs:
  bp_token:
    type: string
    required: true
  bp_workspace_id:
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 8

    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        check-latest: true
        cache: 'pnpm'

    - shell: bash
      run: pnpm i --frozen-lockfile

    - shell: bash
      run: pnpm bp login -y --token ${{ inputs.bp_token }} --workspace-id ${{ inputs.bp_workspace_id }}

    - shell: bash
      working-directory: ./packages/gainzmate
      run: pnpm add:integrations
