name: Deploy Gainzmate

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: ./.github/actions/install
        with:
          bp_token: ${{ secrets.BP_TOKEN }}
          bp_workspace_id: ${{ secrets.BP_WORKSPACE_ID }}
          telegram_bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          gsheets_spreadsheet_id: ${{ secrets.GSHEETS_SPREADSHEET_ID }}
          gsheets_client_email: ${{ secrets.GSHEETS_CLIENT_EMAIL }}
          gsheets_private_key: ${{ secrets.GSHEETS_PRIVATE_KEY }}
      - name: Build
        working-directory: ./packages/gainzmate
        run: pnpm bp build -y
      - name: Deploy
        working-directory: ./packages/gainzmate
        run: |
          pnpm bp deploy --botId ${{ secrets.BP_BOT_ID }} -y --minify false
